export function getSignalingUrl(): string {
  const configured = import.meta.env.VITE_SIGNALING_URL;
  if (configured) return configured;
  const protocol = window.location.protocol === "https:" ? "wss" : "ws";
  return `${protocol}://${window.location.hostname}:8080`;
}

/**
 * Fetch short-lived ICE servers (STUN + TURN credentials) generated by the
 * signaling server. Returns undefined on failure or when TURN is not
 * configured, in which case the default STUN-only config applies.
 */
export async function fetchIceServers(): Promise<RTCIceServer[] | undefined> {
  const httpUrl = getSignalingUrl().replace(/^ws/, "http");
  try {
    const res = await fetch(`${httpUrl}/ice-servers`, { signal: AbortSignal.timeout(4000) });
    if (!res.ok) return undefined;
    const body = (await res.json()) as { iceServers?: RTCIceServer[] | null };
    return body.iceServers?.length ? body.iceServers : undefined;
  } catch {
    return undefined;
  }
}

export function roomUrl(code: string): string {
  return `${window.location.origin}/room/${code}`;
}
